"""initial_schema

Revision ID: 001
Revises: 
Create Date: 2026-06-02 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    op.create_table('summaries_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='summaryperiod'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_udhar_given', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_udhar_taken', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_cache_id'), 'summaries_cache', ['id'], unique=False)
    op.create_index(op.f('ix_summaries_cache_period'), 'summaries_cache', ['period'], unique=False)
    op.create_index(op.f('ix_summaries_cache_user_id'), 'summaries_cache', ['user_id'], unique=False)
    
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.Enum('SALE', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    
    op.create_table('udhar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.Enum('GIVEN', 'TAKEN', name='udhartype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SETTLED', name='udharstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_udhar_customer_name'), 'udhar', ['customer_name'], unique=False)
    op.create_index(op.f('ix_udhar_id'), 'udhar', ['id'], unique=False)
    op.create_index(op.f('ix_udhar_status'), 'udhar', ['status'], unique=False)
    op.create_index(op.f('ix_udhar_user_id'), 'udhar', ['user_id'], unique=False)
    
    op.create_table('gst_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_records_id'), 'gst_records', ['id'], unique=False)
    op.create_index(op.f('ix_gst_records_transaction_id'), 'gst_records', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_gst_records_user_id'), 'gst_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gst_records_user_id'), table_name='gst_records')
    op.drop_index(op.f('ix_gst_records_transaction_id'), table_name='gst_records')
    op.drop_index(op.f('ix_gst_records_id'), table_name='gst_records')
    op.drop_table('gst_records')
    
    op.drop_index(op.f('ix_udhar_user_id'), table_name='udhar')
    op.drop_index(op.f('ix_udhar_status'), table_name='udhar')
    op.drop_index(op.f('ix_udhar_id'), table_name='udhar')
    op.drop_index(op.f('ix_udhar_customer_name'), table_name='udhar')
    op.drop_table('udhar')
    
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    
    op.drop_index(op.f('ix_summaries_cache_user_id'), table_name='summaries_cache')
    op.drop_index(op.f('ix_summaries_cache_period'), table_name='summaries_cache')
    op.drop_index(op.f('ix_summaries_cache_id'), table_name='summaries_cache')
    op.drop_table('summaries_cache')
    
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    
    # Drop enum types manually if needed, but PostgreSQL will drop them when the DB drops
    # Usually we need to execute raw SQL to drop enums
    op.execute('DROP TYPE IF EXISTS summaryperiod CASCADE')
    op.execute('DROP TYPE IF EXISTS transactiontype CASCADE')
    op.execute('DROP TYPE IF EXISTS udhartype CASCADE')
    op.execute('DROP TYPE IF EXISTS udharstatus CASCADE')
    # ### end Alembic commands ###
