"""add_gst_to_transaction

Revision ID: f22ab149fd06
Revises: 001
Create Date: 2026-06-02 03:30:57.104070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22ab149fd06'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('gst_applicable', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('gst_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'gst_rate')
    op.drop_column('transactions', 'gst_amount')
    op.drop_column('transactions', 'gst_applicable')
    # ### end Alembic commands ###
